# kubernetes/backend-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db-pvc
spec:
  accessModes:
    - ReadWriteOnce # Suitable for a single pod database
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
  # storageClassName: standard # Uncomment and specify if needed, otherwise uses default