# kubernetes/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # Selects pods with the label 'app: frontend'
  ports:
    - protocol: TCP
      port: 80 # Port the service will listen on
      targetPort: 80 # Port the container is listening on
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer