name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run backend tests
      run: python run_tests.py
    # Optional: Add steps to build and push Docker image here
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./backend
    #     push: ${{ github.event_name == 'push' }} # Push only on merges to main
    #     tags: your-dockerhub-username/personal-finance-backend:latest # Replace with your Docker Hub username

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Run frontend tests
      run: npm test -- --watchAll=false # Run tests non-interactively
    - name: Build frontend
      run: npm run build
    # Optional: Add steps to build and push Docker image here
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./frontend
    #     push: ${{ github.event_name == 'push' }} # Push only on merges to main
    #     tags: your-dockerhub-username/personal-finance-frontend:latest # Replace with your Docker Hub username
